package org.example.TBFV;

public enum TDValidationStatus {
    SUCCESS,
    PARTIALLY_SUCCESS,
    COUNTER_EXAMPLE,
    UNKNOWN_VARIABLE,
    ABSENCE_EXCEPTION,
    UNEXPECTED_EXCEPTION,
    TESTCASE_GENERATION_FAILED,
    TIMEOUT_ERROR,
    UNEXPECTED_ERROR
}
